var sheetData = [
  {
    name: "Academy of Learning College - Abbotsford",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O212477056057",
    location: "Abbotsford, Langley",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College - Langley",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O212477063807",
    location: "Langley",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College - Victoria",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395300024",
    location: "Kamloops, Kelowna, Nanaimo, Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College – Richmond",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O110096211204",
    location: "Richmond",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College – Surrey",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19361063652",
    location: "Surrey",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College – Vancouver",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19376530942",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Academy of Learning College – Williams Lake",
    url: "http://www.academyoflearning.com/programs_british_columbia",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19376505602",
    location: "Williams Lake",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.academyoflearning.com/images/logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "Acsenda School of Management",
    url: "https://www.acsenda.com",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19278931852",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Alexander College",
    url: "https://alexandercollege.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19347185182",
    location: "Burnaby, Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "https://alexandercollege.ca/beta/wp-content/themes/alexander/images/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Arbutus College of Communication Arts, Business & Technology",
    url: "https://arbutuscollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19219834012",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://arbutuscollege.com/wp-content/themes/arbutus/images/s5_logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Ashton College",
    url: "https://www.ashtoncollege.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19219876582",
    location: "Abbotsford, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.ashtoncollege.ca/wp-content/uploads/2017/06/logo.jpg",
    isAllowedToUseImage: true
  },
  {
    name: "Aveda Institute Vancouver",
    url: "https://www.avedainstitute.ca/vancouver/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: true,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19238753082",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static1.squarespace.com/static/5a386664b1ffb6e54c485e6b/t/5a6505f6c83025655b8350bd/1535059979075/?format=1500w",
    isAllowedToUseImage: false
  },
  {
    name: "Blanche Macdonald Centre",
    url: "https://www.blanchemacdonald.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: true,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19257719332",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Brighton College",
    url: "https://brightoncollege.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19257044542",
    location: "Burnaby, Surrey",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.brightoncollege.com/wp-content/themes/brighton/images/logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "British Columbia Institute of Technology (BCIT)",
    url: "https://www.bcit.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19330128542",
    location: "Burnaby, North Vancouver, Richmond, Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Camber College",
    url: "http://cambercollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19219937972",
    location: "Powell River",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://cambercollege.com/wp-content/uploads/2018/03/world-class_language_education.png",
    isAllowedToUseImage: true
  },
  {
    name: "Camosun College",
    url: "http://camosun.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19361235542",
    location: "Victoria",
    postGraduateWorkPermitExists: true,
    imageUrl: "http://camosun.ca/template/images/logos/camosun-white.png",
    isAllowedToUseImage: true
  },
  {
    name: "Canadian College",
    url: "http://canadiancollege.com/jp/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19352621432",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://canadiancollege.com/img/logos/logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Canadian College of English Language",
    url: "http://canada-english.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19352470312",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://canada-english.com/img/logos/logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Canadian Health Care Academy",
    url: "http://www.chcabc.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19331168352",
    location: "Surrey, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.chcabc.com/wp-content/uploads/2017/09/canadian-4.png",
    isAllowedToUseImage: false
  },
  {
    name: "Canadian Tourism College",
    url: "https://www.tourismcollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: true,
    dli: "O19301323922",
    location: "Surrey, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.tourismcollege.com/wp-content/uploads/2016/07/ctc-logo-white.png",
    isAllowedToUseImage: true
  },
  {
    name: "Capilano University",
    url: "https://www.capilanou.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19280078102",
    location: "North Vancouver, Sechelt",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Capital College",
    url: "https://www.capitalcollege.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283932632",
    location: "Coquitlam, Richmond, Surrey",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static.wixstatic.com/media/c7b717_1060946efdd749ef879592a0badddb7c~mv2_d_1811_1811_s_2.png/v1/fill/w_202,h_202,al_c,usm_0.66_1.00_0.01/c7b717_1060946efdd749ef879592a0badddb7c~mv2_d_1811_1811_s_2.png",
    isAllowedToUseImage: true
  },
  {
    name: "CG Masters School of 3D Animation & VFX",
    url: "https://cg-masters.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19240092592",
    location: "New Westminster",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://cg-masters.com/wp-content/uploads/2018/02/CGM_logo_for_website.png",
    isAllowedToUseImage: true
  },
  {
    name: "Cloud Nine College Ltd.",
    url: "http://www.cloudninecollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19394940242",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.cloudninecollege.com/wp-content/uploads/2016/06/Cloud_Nine_College_logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "CodeCore",
    url: "https://www.codecore.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O116475837179",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.codecore.ca/assets/logo-fd688d22b990e2e634534e25a26afc97.png",
    isAllowedToUseImage: true
  },
  {
    name: "Columbia College",
    url: "https://www.columbiacollege.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19279591302",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Coquitlam College",
    url: "https://www.coquitlamcollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: true,
    dli: "O19244321962",
    location: "Coquitlam",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "https://www.coquitlamcollege.com/wp-content/uploads/2017/10/coquitlamcollege-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Cornerstone International Community College of Canada",
    url: "https://ciccc.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19274576342",
    location: "Richmond, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://ciccc.ca/wp-content/uploads/2015/05/logo5.png",
    isAllowedToUseImage: true
  },
  {
    name: "Create Career College",
    url: "https://www.createcareer.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19275297052",
    location: "Burnaby, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static.wixstatic.com/media/782f22_3da6ce2d3ec2452aab8b1646a840216c~mv2_d_1200_1200_s_2.png/v1/crop/x_238,y_179,w_723,h_860/fill/w_95,h_114,al_c,usm_0.66_1.00_0.01/782f22_3da6ce2d3ec2452aab8b1646a840216c~mv2_d_1200_1200_s_2.png",
    isAllowedToUseImage: true
  },
  {
    name: "Dorset College",
    url: "http://www.dorsetcollege.bc.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: true,
    dli: "O19394940932",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.dorsetcollege.bc.ca/images/dorsetlogorgbspot.svg?crc=201670047",
    isAllowedToUseImage: true
  },
  {
    name: "Douglas College",
    url: "https://www.douglascollege.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19360973702",
    location: "Coquitlam, New Westminster, Surrey",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "https://www.douglascollege.ca/-/media/EFA61F42D12549EAA7E5DCBFB0BAFD3B.ashx",
    isAllowedToUseImage: false
  },
  {
    name: "EC Vancouver",
    url: "https://www.ecenglish.com/en",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19280217882",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "EF International Language Campus",
    url: "https://www.ef.com/ca/ilsd/schools/vancouver/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19314246102",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.languagescanada.ca/web/default/files/public/LC%20Logo_Colour%20(small)%20[Copy%2042238331].jpg",
    isAllowedToUseImage: false
  },
  {
    name: "ELS Language Centers",
    url: "https://www.els.edu/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19360978002",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.languagescanada.ca/web/default/files/public/LC%20Logo_Colour%20(small)%20[Copy%2042238331].jpg",
    isAllowedToUseImage: true
  },
  {
    name: "Emily Carr University of Art and Design",
    url: "https://www.ecuad.ca",
    eslExists: false,
    isPublic: true,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19361259712",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: false
  },
  {
    name: "English as a Second Language International (ESLI)",
    url: "http://www.esli-intl.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19361202892",
    location: "Langley",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.esli-intl.com/images/homepage_logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Eton College",
    url: "http://www.etoncollege.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: true,
    dli: "O19330008162",
    location: "Powell River, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://www.etoncollege.ca/wp-content/uploads/etonlogo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Eurocentres Canada",
    url: "http://www.eurocentrescanam.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19275179522",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.eurocentrescanam.com/wp-content/themes/oxfordinternational-uicenglish/components/header/img/logo.svg%20?%3E",
    isAllowedToUseImage: true
  },
  {
    name: "Fairleigh Dickinson University (Vancouver)",
    url: "https://www.fdu.edu/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19227134842",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "https://www.fdu.edu/view2/140308/images/fdu_logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Franklin English Language College",
    url: "https://www.franklinedu.org/ca/en/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19396094599",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Fraser International College",
    url: "https://www.fraseric.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19239078442",
    location: "Burnaby",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Gastown Business College",
    url: "http://gastownbusinesscollege.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19238785512",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://gastownbusinesscollege.ca/wp-content/uploads/2017/02/logo-6.png",
    isAllowedToUseImage: true
  },
  {
    name: "Gateway College",
    url: "http://www.gwcollege.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19279807782",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static.wixstatic.com/media/ed41e4_a2529113d79741f988cb9c6507d1da16.png/v1/fill/w_410,h_53,al_c,usm_0.66_1.00_0.01/ed41e4_a2529113d79741f988cb9c6507d1da16.png",
    isAllowedToUseImage: true
  },
  {
    name: "GEOS Languages Plus",
    url: "http://www.geosvancouver.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19361015442",
    location: "Vancouver, Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.geosvancouver.com/fileadmin/_migrated/pics/geos-logo66.jpg",
    isAllowedToUseImage: true
  },
  {
    name: "Global College",
    url: "https://gcc-canada.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19347491712",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://gcc-canada.com/wp/wp-content/uploads/2016/09/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Global Village English Centre Victoria",
    url: "https://gvenglish.com",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19319050762",
    location: "Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://gvenglish.com/Themes/GVEnglish/Images/gvenglish-header-2.png",
    isAllowedToUseImage: true
  },
  {
    name: "Global Village Vancouver",
    url: "https://gvenglish.com",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19330822902",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://gvenglish.com/Themes/GVEnglish/Images/gvenglish-header-2.png",
    isAllowedToUseImage: true
  },
  {
    name: "Goh Ballet Academy",
    url: "http://www.gohballet.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O110656686527",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.gohballet.com/wp-content/uploads/2015/09/logo-gohballet.png",
    isAllowedToUseImage: true
  },
  {
    name: "Greystone College of Business and Technology",
    url: "https://www.greystonecollege.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19352522932",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.greystonecollege.com/sites/default/files/GC_Horizontal_Logo_RGB_1.png",
    isAllowedToUseImage: true
  },
  {
    name: "IH Career College",
    url: "http://ihcareercollege.com",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395639240",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "ILAC International College",
    url: "https://www.ilac.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O110957942277",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://46dtbf3k4dl51vghpj6qqocj-wpengine.netdna-ssl.com/wp-content/themes/ilac/img/ILAC-white-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "ILSC Vancouver",
    url: "https://www.ilsc.com/vancouver",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19275396842",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "In Focus Film School",
    url: "https://infocusfilmschool.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395639663",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://infocusfilmschool.com/wp-content/uploads/2018/01/blue-circle-logo-2.png",
    isAllowedToUseImage: false
  },
  {
    name: "inlingua Vancouver dba INVO Career College",
    url: "https://www.invocollege.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19279564092",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static.wixstatic.com/media/c14f0f_90a78441821d4b8d8a04aad0d14e0ced~mv2.png/v1/fill/w_286,h_111,al_c,usm_0.66_1.00_0.01/c14f0f_90a78441821d4b8d8a04aad0d14e0ced~mv2.png",
    isAllowedToUseImage: true
  },
  {
    name: "inlingua Victoria College of Languages",
    url: "https://www.inlinguavictoria.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19350928592",
    location: "Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.inlinguavictoria.com/wp-content/uploads/2018/04/inlingua-Victoria-Logo-black-1.png",
    isAllowedToUseImage: true
  },
  {
    name: "Institute of Technology Development of Canada (ITD)",
    url: "https://www.itdcanada.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19279542632",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://itdcanada.ca/wp-content/uploads/2018/07/cropped-logo-300x127.png",
    isAllowedToUseImage: true
  },
  {
    name: "International House Vancouver",
    url: "http://www.ihvancouver.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19279619012",
    location: "Vancouver, Whistler",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.ihvancouver.com/img/logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "International Language Academy of Canada (ILAC)",
    url: "https://www.ilac.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283901032",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://46dtbf3k4dl51vghpj6qqocj-wpengine.netdna-ssl.com/wp-content/themes/ilac/img/ILAC-white-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "iTTTi Vancouver",
    url: "http://www.ittti.ca/j",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19274183992",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.ittti.ca/ittti/wp-content/uploads/2018/04/iTTTi_logo2.png",
    isAllowedToUseImage: true
  },
  {
    name: "JCI Institute",
    url: "https://www.jcinstitute.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: true,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283904182",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.jcinstitute.com/wp-content/themes/jci/images/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Kaplan International Vancouver",
    url: "https://www.kaplaninternational.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19394941182",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://cdn.kaplaninternational.com/profiles/base_drupal_build/themes/kis_theme/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Kwantlen Polytechnic University",
    url: "http://www.kpu.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19350676872",
    location: "Cloverdale, Langley, Richmond,Surrey",
    postGraduateWorkPermitExists: true,
    imageUrl: "http://www.kpu.ca/sites/all/themes/kwantlen_v3/img/logo.svg",
    isAllowedToUseImage: false
  },
  {
    name: "Langara College",
    url: "https://langara.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19319074622",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Language Studies International (LSI)",
    url: "https://www.lsi.edu/en/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283928542",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.lsi.edu/assets/v4/images/logos/lsi_1965_white_logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Languages Across Borders",
    url: "http://www.languagesacrossborders.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19274549462",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "LaSalle College",
    url: "http://www.lasallecollegevancouver.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: true,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19275426742",
    location: "Kamloops, Vancouver, Victoria",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "http://www.lasallecollegevancouver.com/~/media/images/responsive/vancouver/home-page/college-in-vancouver.ashx",
    isAllowedToUseImage: true
  },
  {
    name: "London School",
    url: "http://www.londonschool.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: true,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19352116052",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Lost Boys Studios - School of Visual Effects",
    url: "https://lostboys-studios.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19274961822",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Montessori Training Centre of British Columbia",
    url:
      "http://www.teach-montessori.org/blog/training_facility/montessori-training-centre-of-british-columbia/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19301054682",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://live-teach-montessori.pantheon.io/wp-content/uploads/2015/02/cropped-logo-blue.png",
    isAllowedToUseImage: false
  },
  {
    name: "New Image College",
    url: "http://www.newimage.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: true,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19274696442",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.newimage.ca/wp-content/uploads/2018/04/logo-black-2.png",
    isAllowedToUseImage: true
  },
  {
    name: "OHC Vancouver",
    url: "https://www.ohcenglish.com",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19394452186",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://www.ohcenglish.com/templates/images/Top-banner-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Okanagan College",
    url: "https://www.okanagan.bc.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19395299488",
    location:
      "Kelowna, Oliver, Penticton, Revelstoke, Salmon Arm, Summerland, Vernon",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Omni College",
    url: "https://www.omnicollege.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19347439002",
    location: "Richmond",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.omnicollege.com/wp-content/uploads/images/website/header-bg.jpg",
    isAllowedToUseImage: true
  },
  {
    name: "Pacific Rim Early Childhood Institute",
    url: "https://www.earlychildhoodeducator.com/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19394451698",
    location: "Saanichton",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: false
  },
  {
    name: "RED Academy",
    url: "https://redacademy.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O132321964227",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://redacademy.com/content/uploads/2017/07/RED-Logos-RGB-01.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Royal Roads University",
    url: "http://www.royalroads.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19330635812",
    location: "Victoria",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "http://www.royalroads.ca/sites/all/themes/custom/rru_base/images/header-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "SELC Career College Vancouver",
    url: "https://selccareercollege.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395639791",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://dslhzdv221fe8.cloudfront.net/wp-content/uploads/2016/09/selccareercanada_logo1.png",
    isAllowedToUseImage: true
  },
  {
    name: "SELC English Language Centre Canada",
    url: "https://selceducation.com/canada/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19330751052",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://d2qh7x6mltq9ao.cloudfront.net/canada/wp-content/uploads/2016/08/logo-selc-vancouver.png",
    isAllowedToUseImage: true
  },
  {
    name: "Selkirk College",
    url: "http://selkirk.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19360990072",
    location: "Castlegar, Grand Forks, Kaslo Centre, Nakusp, Nelson, Trail",
    postGraduateWorkPermitExists: true,
    imageUrl: "http://selkirk.ca/sites/all/themes/selkirk/SelkirkLogo_00.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Simon Fraser University (SFU)",
    url: "https://www.sfu.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O18781994282",
    location: "Burnaby, Surrey, Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: false
  },
  {
    name: "Sprott Shaw College",
    url: "https://sprottshaw.com/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19278865162",
    location:
      "Abbotsford, Burnaby, Chilliwack, Kamloops, Kelowna, Maple Ridge, Nanaimo, New Westminster, Osoyoos, Penticton, Richmond, Surrey, Vancouver, Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://36umeu3126ra2winlrma23x6-wpengine.netdna-ssl.com/wp-content/themes/sprott/img/logos/sprottshaw_logo_compressed.png",
    isAllowedToUseImage: true
  },
  {
    name: "Sprott Shaw Language College",
    url: "http://www.studysslc.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283917732",
    location: "Surrey, Vancouver, Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://i1.wp.com/www.studysslc.com/wp-content/uploads/2017/04/new-web-logo-sslc.png?fit=120%2C60",
    isAllowedToUseImage: true
  },
  {
    name: "St. George International College",
    url: "https://www.sgiccanada.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19352161652",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://static.wixstatic.com/media/6ed5e0_136910cbe56c4b888462e80f591ab83a~mv2_d_10787_3583_s_4_2.png/v1/fill/w_210,h_70,al_c,usm_0.66_1.00_0.01/6ed5e0_136910cbe56c4b888462e80f591ab83a~mv2_d_10787_3583_s_4_2.png",
    isAllowedToUseImage: true
  },
  {
    name: "St. Giles Vancouver",
    url: "https://www.stgiles-international.com/vancouver/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395299510",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://www.stgiles-international.com/images/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Stenberg College",
    url: "https://www.stenbergcollege.com",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283910772",
    location: "Duncan, Kamloops, Surrey, Vernon",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://stenbergcollege.com/wp-content/uploads/2017/05/stenberg_logo_blue-540-2.png",
    isAllowedToUseImage: false
  },
  {
    name: "Sterling College",
    url: "https://www.sterlingcollege.ca/creative-technology-programs/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19279828772",
    location: "Surrey, Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://sterlingcollege.ca/newwebsite/wp-content/uploads/2017/12/sterlingcollege_logo_white.png",
    isAllowedToUseImage: true
  },
  {
    name: "Tamwood Careers",
    url: "https://www.tamwoodcareers.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19361007342",
    location: "Vancouver, Whistler",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.tamwoodcareers.com/wp-content/uploads/2017/08/Tamwood-Logo-blue-white-e1512234418928.png",
    isAllowedToUseImage: true
  },
  {
    name: "Tamwood Language Centre",
    url: "https://www.tamwood.com",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19280516442",
    location: "Vancouver, Whistler",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://www.tamwood.com//escudo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Think Tank Training Centre",
    url: "https://www.tttc.ca/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395299578",
    location: "North Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "https://www.tttc.ca/wp-content/uploads/2017/02/logo-test-training-centre.jpg",
    isAllowedToUseImage: false
  },
  {
    name: "Thompson Rivers University",
    url: "https://www.tru.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19395299610",
    location: "Kamloops, Williams Lake",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "https://www.tru.ca/__shared/templates/2016/images/truLogo-reverse.png",
    isAllowedToUseImage: true
  },
  {
    name: "Trinity Western University",
    url: "https://www.twu.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19347055392",
    location: "Langley, Richmond",
    postGraduateWorkPermitExists: true,
    imageUrl: "https://www.twu.ca/sites/default/files/footer-logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "University of British Columbia (UBC)",
    url: "https://www.ubc.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19330231062",
    location: "Kelowna, Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: false
  },
  {
    name: "University of Northern British Columbia",
    url: "https://www.unbc.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19283889692",
    location: "Fort St. John, Prince George, Quesnel, Terrace",
    postGraduateWorkPermitExists: true,
    imageUrl: "https://www.unbc.ca/sites/default/files/unbc-logo.png",
    isAllowedToUseImage: false
  },
  {
    name: "University of the Fraser Valley",
    url: "https://www.ufv.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19395299642",
    location: "Abbotsford, Chilliwack, Hope, Mission",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "https://www.ufv.ca/media/2015/brand/UFV_University-of-the-Fraser-Valley.png",
    isAllowedToUseImage: true
  },
  {
    name: "University of Victoria",
    url: "https://www.uvic.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19280533442",
    location: "Victoria",
    postGraduateWorkPermitExists: true,
    imageUrl: "",
    isAllowedToUseImage: false
  },
  {
    name: "Vancouver Career College",
    url: "http://www.career.college/",
    eslExists: false,
    isPublic: false,
    eceExists: true,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395299664",
    location:
      "Abbotsford, Burnaby, Chilliwack, Coquitlam, Kelowna, Richmond, Surrey, Vancouver, Victoria",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver Community College",
    url: "http://www.vcc.ca/",
    eslExists: false,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: true,
    businessExists: false,
    degreeExists: true,
    universityTransferExists: true,
    dli: "O19279717512",
    location: "Vancouver",
    postGraduateWorkPermitExists: true,
    imageUrl:
      "http://www.vcc.ca/media/vancouver-community-college/style-assets/css/style-images/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver Film School",
    url: "https://vfs.edu",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19239015912",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver Institute of Media Arts (VanArts)",
    url: "https://www.vanarts.com/",
    eslExists: false,
    isPublic: false,
    eceExists: false,
    itExists: true,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19331363352",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://www.vanarts.com/drive/uploads/2017/01/footer-logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver International College",
    url: "http://www.vicenglish.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283898312",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "http://www.vicenglish.com/img/logo.png",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver Island University",
    url: "https://www.viu.ca/",
    eslExists: true,
    isPublic: true,
    eceExists: true,
    itExists: true,
    beautyExists: false,
    businessExists: true,
    degreeExists: true,
    universityTransferExists: false,
    dli: "O19395299688",
    location: "Duncan, Nanaimo, Parksville, Powell River",
    postGraduateWorkPermitExists: true,
    imageUrl: "https://www.viu.ca/profiles/viu/themes/viu_theme/logo.svg",
    isAllowedToUseImage: true
  },
  {
    name: "Vancouver Premier College of Hotel Management",
    url: "http://www.vpcollege.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: true,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19280589592",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl:
      "http://www.vpcollege.com/wp-content/uploads/2014/02/VPCWEBLOGO_100_two-lines_two-fonts.png",
    isAllowedToUseImage: true
  },
  {
    name: "VanWest College (Kelowna)",
    url: "https://vanwest.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19395299852",
    location: "Kelowna",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://vanwest.com/app/assets/VanWest_College.png",
    isAllowedToUseImage: true
  },
  {
    name: "VanWest College (Vancouver)",
    url: "https://vanwest.com/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19283891072",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://vanwest.com/app/assets/VanWest_College.png",
    isAllowedToUseImage: true
  },
  {
    name: "VGC International College",
    url: "http://www.vgc.ca/",
    eslExists: true,
    isPublic: false,
    eceExists: false,
    itExists: false,
    beautyExists: false,
    businessExists: false,
    degreeExists: false,
    universityTransferExists: false,
    dli: "O19386095472",
    location: "Vancouver",
    postGraduateWorkPermitExists: false,
    imageUrl: "https://vgc.ca/wp-content/uploads/2018/07/Newlogo_100px.png",
    isAllowedToUseImage: true
  }
];
